version: '3.9'

services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=admin

  aplikacja:
    image: xd:xd4
    ports:
      - 8080:8080
    depends_on:
      - postgres
        # command: java -jar ./etl-app-1.0-SNAPSHOT.jar
