name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag maks0x073/etl-app:latest
    - name: Push to DockerHub
      run: |
        docker login -u maks0x073 -p ${{  secrets.DOCKER_HUB_TOKEN  }}
        docker push maks0x073/etl-app:latest
